# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: CLEDemandsjustice.org
description: '#CLEDemands Justice'


media:
  contact:
    name: New Abolitionists Association
    email: jworthy@childrensdefense.org

memorial:
  headline: 'In 10 days, we lost two lives to police'
  lead: ''

tanisha:
  name: 'Tanisha Anderson'
  years: '1977 - 2014'
  image: tanisha.jpg
  story: ''

tamir:
  name: 'Tamir Rice'
  years: '2001 - 2014'
  image: 'tamir.jpg'
  story: ''

newsletter:
  headline: 'Sign up for Updates'
  interest: "I'm interested in:"
  submit: 'Get updates'

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: pretty
paginate: 0
paginate_path: 'page:num'

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

pygments: false

collections:
  demands:
    output: false


prose:
  rooturl: 'app'
  siteurl: 'http://new-abolitionists-ohio.github.io/'
  media: 'img'
  ignore:
    - index.md
    - _config.yml
    - /app/_layouts
    - /app/_plugins
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Actions"
              value: "actions"
            - name: "Trainings"
              value: "trainings"
            - name: "Demands"
              value: "demands"
            - name: "Negotiations"
              value: "negotiations"
            - name: "Trainings"
              value: "trainings"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
