# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml


# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico', 'node_modules/**/*']

include: ['.htaccess', 'sitemap.xml']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: pretty
paginate: 12
paginate_path: 'page:num'

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: false

collections:
  demands:
    output: false

# gems:
#   - jekyll-sitemap

prose:
  rooturl: 'app'
  siteurl: 'http://cledemandsjustice.org'
  media: 'img'
  ignore:
    - index.md
    - _config.yml
    - /app/_layouts
    - /app/_plugins
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Actions"
              value: "actions"
            - name: "Trainings"
              value: "trainings"
            - name: "Demands"
              value: "demands"
            - name: "Negotiations"
              value: "negotiations"
            - name: "Trainings"
              value: "trainings"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
