# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml


# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico', 'node_modules/**/*']

include: ['.htaccess', 'sitemap.xml']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: pretty
paginate: 12
paginate_path: 'page:num'

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: false

# pandoc:
#   skip: false
#   # impose: true
#   output: /pandoc
#   site_flags: '--toc'
#   outputs:
#     pdf:
#     epub:
#     docx:
#     markdown:

# gems:
#   - jekyll-pandoc-multiple-formats

prose:
  rooturl: 'app'
  siteurl: 'http://cledemandsjustice.org'
  media: 'img'
  ignore:
    - index.md
    - _config.yml
    - /app/_layouts
    - /app/_plugins
    - /app/_site
    - /app/js
    - /app/_less
    - /app/css
    - /app/CNAME
    - /app/google3ddf1910d6053919.html
    - /app/sitemap.xml
  metadata:
    app/_posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
          placeholder: "We demand..."
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
    app/_posts/demands:
      - name: "title"
        field:
          element: "text"
          label: "title"
          placeholder: "We demand..."
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "category"
        field:
          element: "hidden"
          value: "demands"
      - name: "type"
        field:
          element: "multiselect"
          label: "Type of Demand"
          placeholder: "Choose Type"
          options:
            - name: "Council Resolution"
              value: "resolution"
            - name: "Council Ordinance"
              value: "ordinance"
            - name: "For Immediate Implementation"
              value: "immediate"
